language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: w76/NVnCP/6TDczvnChlJpoZ1HSp5VOCgwqHjBcRqwn4OQiZ75FoGnhTm/W+aOSIFVDi//z9hi4gBCd9rbp5sgWB3f1PSYoNx2FaaWq7TBvL9XxdBBtSTyXCievivo5bNUpl5HAH+SVGP3TvKSbeuy3/kNbHHSSJopNhTM274amrUJvt26QMvDPt6jreWDFB55j+1S/aRBlFZwqw+92/IL8OqxXJ2Lqv9LJFSEIfa4sI91KDzBHsFjBt6lpgG/WPMmyZQDcQ5+obmhJgzrleiL71QhYidfyxW+rncMSsC9+AtTo+xwlWNcTIEgVS/twfEc4+sromwkD4LnhlL9QdX/yUS8v7riP4QxmRzmkdgqgb2AXdlQUDhLmyGvfE2gVFB88iqYiA6YjvhEU2Gazw0f9oN7XDekS0o2cHkw6wbYi8mSFzTi2v2rHlT/2VMHhkrslKdXpjxEkvCmC/vZV5XWV9QDbnXBuwH68X4rXNWvtOzSx49MrtMnNCUh4DawSe0epZm4CB11YFT7hat4gB+gv9dNzwg626DinAicObE782IriCeo188QNeeKLlIZvZphP+7/ufjnfzXfJLxd+Im58v2GmX/K4fXBN81ieZYfu44beM/ilNWHKOTFMDeTUvbae9z0lwlEstEUVjeo7kJWCMVvTnuCNd0CjQvRpnYi0=
  file: app/build/outputs/apk/app*release*.apk
  file_glob: true
  skip_cleanup: true
  on:
    repo: JackDn/NL2App
    tags: true
before_install: gpg --passphrase $FILE_KEY KeyStore.jks.gpg
